[package]
name = 'my_todo_list'
version = '1.0.0'

[addresses]
todolist_addr='_'
Std = "0x1"
aptos_std = "0x1"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'aptos-framework-v1.2.0',subdir = 'aptos-move/framework/aptos-framework' }
AptosToken = {  git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'aptos-framework-v1.2.0', subdir = "aptos-move/framework/aptos-token" }
AptosStdlib = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'aptos-framework-v1.2.0', subdir = "aptos-move/framework/aptos-stdlib" }